- datasource-subsystem/src/main/java/org/wildfly/swarm/examples/ds/subsystem/Main.java
While trying out the datasources example I got an exception that the driver name wasn't set - I saw there was a org.wildfly.swarm.datasources.JdbcDriver that does set the name (as opposed to org.wildfly.swarm.config.datasources.JdbcDriver which was used). Not sure if it's the correct way to go but it works ;)
Was trying this against HEAD of Swarm Alpha5.
> Ensure driverName is set by using org.wildfly.swarm.datasources.JdbcDriver

- messaging/messaging-clustering/pom.xml
add swarm.bind.address=127.0.0.1 & java.net.preferIPv4Stack=true to
ensure that JGroups does not complain about binding to 0.0.0.0.
This error was preventing mvn verify to pass.
JIRA: https://issues.jboss.org/browse/SWARM-121
> [SWARM-121] Enable clustering for messaging

- gradle/README.md
- gradle/build.gradle
Gradle build for gradle example fails because of missing version
and missing dependency. Usage refers to the wrong jar name.
Changes version in build.gradle file to 1.0.0.Final and adds redhat
maven repo for javax.el-impl.3.0.1-b08-jbossorg-1. README.md updated
to point to correct jar file name.
> [SWARM-336], [SWARM-541] Fix gradle build

- jpa/jpa-shrinkwrap/README.md
Switching deployment archive to `WARArchive` allowed imports in `Main.java` to resolve with Maven coordinates `org.wildfly.swarm:bom:1.0.0.Final`
> Corrected the ShrinkWrap-generated archive

- datasource/datasource-subsystem/src/main/java/org/wildfly/swarm/examples/ds/subsystem/Main.java
Motivation
----
Currently its not possible to easily modify this example to use the underlying connection class as the driver jar is in a module.
Modifications
----
Add the module that has been loaded for a specific driver to the deployment so its on the classpath
Result
----
No CNFEs when modifying the example to access the underlying connection class.
> Subject: SWARM-564 Update example

- datasource/datasource-deployment/src/main/java/org/wildfly/swarm/examples/ds/deployment/MyResource.java
Utilize Java 7's try-with-resource syntax to remove boiler-plate code
from this example.
> datasource-deployment: use try-with-resource

- jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta-shrinkwrap/src/it/java/org/wildfly/swarm/it/jpajaxrscdijta/JPAJAXRSCDIJTAApplicationIT.java
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta-shrinkwrap/src/main/java/org/wildfly/swarm/examples/jpajaxrscdijta/EmployeeResource.java
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta-war/src/it/java/org/wildfly/swarm/it/jpajaxrscdijta/JPAJAXRSCDIJTAApplicationIT.java
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta-war/src/main/java/org/wildfly/swarm/examples/jpajaxrscdijta/EmployeeResource.java
Motivation
----------
Both the JPA+JAX-RS+CDI+JTA examples have the following exceptions
in the log:
Could not find MessageBodyWriter for response object of type:
java.lang.Integer of media type: text/html
yet the tests don't fail. This is because the FEST Assert API
is used wrongly and no assertions are actually made.
Modifications
-------------
Fix usage of the FEST Assert API so that asserts are actually made.
This itself makes the tests fail, but that is easy to fix: just
make the int-returning JAX-RS methods @Produces("text/plain"),
so that java.lang.Integer marshaller is found.
Result
------
More test coverage, less exceptions in the log, tests still pass.
> SWARM-806: JPA+JAX-RS+CDI+JTA examples have wrong assertions

- camel/camel-jpa/pom.xml
- config-options/cdi-injection/pom.xml
- docker/docker-jaxrs-dockerfile/pom.xml
- docker/docker-jaxrs/pom.xml
- jaxrs/jaxrs-cdi-deltaspike/pom.xml
- jaxrs/jaxrs-deltaspike-data/pom.xml
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta-shrinkwrap/pom.xml
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-shrinkwrap/pom.xml
- messaging/messaging-mdb/pom.xml
- security/jaas/basic/pom.xml
Motivation
----------
As the jaxrs-cdi fraction is now implicitly brought in from jaxrs, our examples don't need to specify it directly.
Modifications
-------------
Remove jaxrs-cdi from examples, replacing with jaxrs and cdi where necessary
Result
------
No change to behavior of examples
> SWARM-714: Modify examples to not use jaxrs-cdi

- camel/camel-mail/src/main/java/org/wildfly/swarm/examples/camel/mail/Main.java
- not create 2 SMTP servers.
- use an integer instead of an integer-shaped string.
> Change Camel-Mail example to

- config-options/standalone.xml
- config-options/xml-configuration/README.adoc
- config-options/xml-configuration/pom.xml
- config-options/xml-configuration/src/it/java/org/wildfly/swarm/examples/config/subsystem/XmlConfigIT.java
- config-options/xml-configuration/src/main/java/org/wildfly/swarm/examples/config/xml/MyResource.java
Motivation
----------
Forgot to add details of setting standalone.xml on command line
Modifications
-------------
Move standalone.xml out of current directory so it isn't picked up automatically, and then set `-c` on plugin to pass it in.
Result
------
No product impact, fix example to be clearer
> SWARM-856: Cleanup main() examples

- pom.xml
Motivation
----------
Now SNAPSHOT artifacts is deployed on Maven Central,
examples should point it.
Modifications
-------------
Change the SNAPSHOT repo.
Result
------
No impact to product.
> SWARM-997: Change SNAPSHOT repository to Maven Central

- pom.xml
Motivation
----------
The current Drone version has issues with the PhantomJS Driver in Windows
Modifications
-------------
Upgraded to Drone 2.0.1.Final and Arquillian 1.1.12.Final
Result
------
Tests should pass on Windows. No code changes needed
> SWARM-1015: Upgrade to Arquillian Drone 2.0.1.Final and Arquillian 1.1.12.Final

- gradle-mail/src/main/java/org/wildfly/swarm/examples/mail/Main.java
- jaxrs/scala/src/main/scala/org/wildfly/swarm/examples/scala/Main.scala
- messaging/messaging-clustering/src/main/java/org/wildfly/swarm/examples/messaging/clustering/Main.java
- resource-adapter/resource-adapter-deployment/src/main/java/org/wildfly/swarm/examples/rar/deployment/Main.java
- ribbon-secured/events/src/main/java/org/wildfly/swarm/examples/netflix/ribbon/events/Main.java
- ribbon-secured/frontend/src/main/java/org/wildfly/swarm/examples/netflix/ribbon/frontend/Main.java
- ribbon-secured/time/src/main/java/org/wildfly/swarm/examples/netflix/ribbon/time/Main.java
Motivation
----------
Some examples use the deprecated Container class. It should use Swarm instead
Modifications
-------------
The code was updated to use the correct class
Result
------
CI server should be happy
> SWARM-1042: Some examples use Container instead of Swarm

- pom.xml
Motivation
----------
When building wildfly-swarm with an alternate settings.xml via mvn -s ..., arquillian tests still use the default one.
Modifications
-------------
See: https://github.com/wildfly-swarm/wildfly-swarm/pull/384
Result
------
See: https://github.com/wildfly-swarm/wildfly-swarm/pull/384
> SWARM-1141: Pass user defined settings.xml to arquillian tests

- resource-adapter/resource-adapter-deployment/src/main/java/org/wildfly/swarm/examples/rar/deployment/FileIOBean.java
- resource-adapter/resource-adapter-deployment/src/main/java/org/wildfly/swarm/examples/rar/deployment/Main.java
Motivation:
Using an RA from a deployment failed when actually tested.
Changes:
Replace the duplication of classes with a dependency between the
app and the RA deployment.
Result:
It works and actually tests something.
> SWARM-1279 - Fix RA deployment example

- gradle-mail/build.gradle
- gradle-mail/src/main/java/org/wildfly/swarm/examples/mail/Main.java
- gradle/build.gradle
Motivation
----------
When developing with gradle and I saw that the gradle example is very old. Updated it for the Swarm version 2017.7.
[SWARM-1021](https://issues.jboss.org/browse/SWARM-1021)
-----
> Fixed Gradle example for Swarm version 2017.7.x

- management-console/src/main/resources/project-defaults.yaml
The console didn't work for me when importing the dependencies outlined in the `Readme` into my own project.
Based on the documentation at https://reference.wildfly-swarm.io/v/2017.10.0/fractions/management.html `allowed-origin` should be renamed to `allowed-origins` and converted to a list for it to work.
> Fix management console example

- spring/pom.xml
- spring/spring-data/src/main/java/org/wildfly/swarm/examples/springdata/service/EmployeeServiceImpl.java
Motivation
----------
Error when GETting specific resource.
Also update to latest Spring and Spring Data versions.
Modifications
-------------
Replace `getOne()` with `findOne()` and update versions of Spring framework.
Result
------
Fixes Spring Example errors
> SWARM-842: Could not initialize Spring proxy

- datasource/datasource-war/pom.xml
I am updating to the latest JDBC (4.2) driver for Postgres.
The version scheme for the drive has been changed, and the version number now thankfully no longer implies any JDBC or Psql server versions. See here:
https://jdbc.postgresql.org/documentation/faq.html#versioning
> Use latest version, and less confusing version scheme

- camel/camel-jms/src/main/resources/project-defaults.yml
Motivation
----------
Recently, default configuration of the `messaging` fraction changed
to closely match default configuration of the `messaging-activemq`
subsystem in WildFly.
As part of that change, we now configure the `address-setting`,
with a couple of unrelated options. However, the mere fact of
adding a configuration of `address-setting` causes the subsystem
to override default behavior of ActiveMQ Artemis in one important
aspect: automatic creation of queues and topics.
ActiveMQ Artemis, by default, enables queues and topics to be
automatically created on demand and automatically dropped
when empty and without consumers. The `messaging-activemq`
subsystem in WildFly overrides this default, to match behavior
of the legacy `messaging` subsystem based on HornetQ.
This override …
> SWARM-1983: update default fraction configuration to WildFly 11

- pom.xml
Motivation
----------
As part of the rename from WildFly Swarm to Thorntail, the `uberjar`
profile in Examples was changed to set the `thorntail.useUberJar`
property instead of `wildfly-swarm.useUberJar`. That change was
wrong. To keep backwards compabitility, we still use the old name
`wildfly-swarm.useUberJar`.
Modifications
-------------
Restore the original property name.
Result
------
The `uberjar` profile works again.
> THORN-2168: the "uberjar" profile in Examples no longer works

- gradle-examples/README.md
- gradle-examples/jaxrs-cdi/settings.gradle
- gradle-examples/multi-module/build.gradle
- gradle-examples/multi-module/library-module/build.gradle
- gradle-examples/multi-module/settings.gradle
- gradle-examples/multi-module/web-app/build.gradle
* Showcase compatibility of Gradle 5 preview feature around improved Maven BOM dependency constraints.
* Verify that the latest Gradle Arquillian adapter changes are working as expected.
> Update Gradle multi-module project example.

- gradle-examples/README.md
- gradle-examples/multi-module/build.gradle
- gradle-examples/multi-module/gradle.properties
- gradle-examples/multi-module/library-module/src/test/resources/arquillian.xml
- gradle-examples/multi-module/web-app/src/test/java/org/wildfly/swarm/examples/gradle/ArqWarDeploymentTest.java
- gradle-examples/multi-module/web-app/src/test/resources/arquillian.xml
* Updated the README with instructions.
* Configured JaCoCo on the multi-module project.
> [Gradle Examples] Instructions for enabling the JaCoCo agent for Arquillian based tests

- flyway/README.md
- jsf/README.md
- kitchensink-html5-mobile/README.md
- microprofile/README.md
Corrected capitalization that prevented maven dependencies from working, in many cases the opening tag <groupId> was spelled <groupid> conflicting with closing tag.
> Corrected capitalization that prevented maven dependencies from working when copied from MDs

- docker/docker-jaxrs-hollow/Dockerfile
- docker/docker-jaxrs-hollow/README.adoc
- docker/docker-jaxrs-hollow/application/pom.xml
- docker/docker-jaxrs-hollow/application/src/main/java/org/wildfly/swarm/example/docker/JaxRsApplication.java
- docker/docker-jaxrs-hollow/application/src/main/java/org/wildfly/swarm/example/docker/MyResource.java
- docker/docker-jaxrs-hollow/hollow-jar/pom.xml
- docker/docker-jaxrs-hollow/pom.xml
Hey @kenfinnigan et al., this adds an example for using a hollow JAR in a layered Docker image, avoiding repeated invocations of the Thorntail plug-in and recreation of large image layers with the uberjar, provided the application's dependencies haven't changed.
> Adding hollow JAR example

- messaging/messaging-clustering/src/main/resources/project-defaults.yaml
https://issues.jboss.org/browse/THORN-2332
* Discovery and broadcast cluster names has to match, otherwise discovery won't receive messages from broadcast.
* `jgroups-channel` seems to be just renamed to `jgroups-cluster` attribute in Wildfly [1], so `channel` seems to be kind of deprecated, although documentation doesn't mention that.
[1] https://github.com/wildfly/wildfly/blob/master/messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupAdd.java#L75
> THORN-2332 Artemis cluster doesn't form in messaging-clustering QS

- gradle-examples/ejb-jaxrs-mail/build.gradle
- gradle-examples/jaxrs-cdi/build.gradle
- gradle-examples/jpa-jaxrs-cdi/build.gradle
- gradle-examples/multi-module/build.gradle
...so that tt-examples master branch builds without having to install current
tt master locally.
https://issues.jboss.org/browse/THORN-2310
> THORN-2310 Add snapshot repository to gradle examples

- pom.xml
THORN-2391: Unable to build thorntail-examples with different value for version.thorntail.
Motivation
----------
Parent pom.xml contains wrong version references for two dependencies (io.thorntail:arquillian and io.thorntail:bom-all).
Modifications
-------------
Made changes in https://github.com/thorntail/thorntail-examples/blob/master/pom.xml lines #204, #225 replace with '<version>${version.thorntail}</version>'.
Result
------
Will result in better developers experience.
> THORN-2391: Unable to build thorntail-examples with different value for version.thorntail.

- pom.xml
Motivation
----------
In https://github.com/thorntail/thorntail/pull/1299, we removed
the `wildfly-swarm.useUberJar` system property. Examples need
to follow suit.
Modifications
-------------
Use `thorntail.useUberJar` instead of `wildfly-swarm.useUberJar`.
Result
------
Uberjar examples will work with upcoming Thorntail release.
> THORN-2419: remove wildfly-swarm.useUberJar

- vaadin/vaadin14/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build
