thorntail/thorntail-examples

- pom.xml
Fix JDK to version 8 as for wildfly-swarm.
Also dix source encoding to UTF-8.
> Fix jdk versione and source encoding

- jsf/pom.xml
- jsf/src/main/java/org/wildfly/swarm/examples/jsf/Message.java
- jsf/src/main/webapp/WEB-INF/template.xhtml
- jsf/src/main/webapp/WEB-INF/web.xml
- jsf/src/main/webapp/index.html
- jsf/src/main/webapp/index.xhtml
- pom.xml
@kenfinnigan Thank you very much for https://github.com/wildfly-swarm/wildfly-swarm/issues/85 !
This PR is a copy of your functional test for JSF. Reading [your comment](https://github.com/wildfly-swarm/wildfly-swarm/blob/master/integration-tests/jsf/src/test/java/org/wildfly/swarm/integration/jsf/JSFTest.java#L18), I changed some codes for JSF-CDI issue, and it works.
https://issues.jboss.org/browse/WFLY-4889
The changes are ...
* [Add weld dependency](https://github.com/wildfly-swarm/wildfly-swarm-examples/compare/master...emag:jsf-example?expand=1#diff-ea54b65a766f6b05716672480e3d722dR50)
* [Use @ Model instead of @ Named](https://github.com/wildfly-swarm/wildfly-swarm-examples/compare/master...emag:jsf-example?expand=1#diff-e94bf5c654a9ac8b7aad3a200bf11f47R8)
Do you have any plan to …
> JSF Example

- jsf/README.md
> Add README

- msc/README.md
- msc/src/main/java/org/wildfly/swarm/examples/msc/Main.java
- msc/src/main/java/org/wildfly/swarm/examples/msc/MyServiceActivator.java
Updated to show the args set on the container as well as retrieving these in the activator so they could be used by its services.
> Updated to show the args set on the container

- pom.xml
- vaadin/README.md
- vaadin/pom.xml
- vaadin/src/main/java/org/wildfly/swarm/examples/cdi/Greeter.java
- vaadin/src/main/java/org/wildfly/swarm/examples/cdi/VaadinUI.java
A minimalistic Vaadin usage example.
> Vaadin example

- jaxrs/pom.xml
- jaxrs/scala/README.md
- jaxrs/scala/pom.xml
- jaxrs/scala/src/it/java/org/wildfly/swarm/it/scala/JAXRSApplicationIT.java
- jaxrs/scala/src/main/scala/org/wildfly/swarm/examples/scala/Main.scala
- jaxrs/scala/src/main/scala/org/wildfly/swarm/examples/scala/ScalaResource.scala
```
[INFO] Reactor Summary:
[INFO] 
[INFO] WildFly Swarm Examples: Parent ..................... SUCCESS [  1.235 s]
[INFO] WildFly Swarm Examples: Base ....................... SUCCESS [  0.636 s]
[INFO] WildFly Swarm Examples: Datasource parent .......... SUCCESS [  0.049 s]
[INFO] WildFly Swarm Examples: Datasource Deployment ...... SUCCESS [  9.437 s]
[INFO] WildFly Swarm Examples: Datasource Subsystem ....... SUCCESS [  9.599 s]
[INFO] WildFly Swarm Examples: JAX-RS parent .............. SUCCESS [  0.050 s]
[INFO] WildFly Swarm Examples: JAX-RS .war ................ SUCCESS [  7.842 s]
[INFO] WildFly Swarm Examples: JAX-RS ShrinkWrap .......... SUCCESS [  7.481 s]
[INFO] WildFly Swarm Examples: JAX-RS and CDI ............. SUCCESS [ 13.552 s]
[INFO] WildFly Swarm Examples: Consumer …
```
> new scala example

- jaxws/README.md
- jaxws/pom.xml
- jaxws/src/it/java/org/wildfly/swarm/examples/jaxws/Client.java
- jaxws/src/it/java/org/wildfly/swarm/examples/jaxws/ClientIT.java
- jaxws/src/it/java/org/wildfly/swarm/examples/jaxws/JAXWSApplicationIT.java
- jaxws/src/main/java/org/wildfly/swarm/examples/jaxws/HelloWorldService.java
- jaxws/src/main/java/org/wildfly/swarm/examples/jaxws/HelloWorldServiceImpl.java
- jaxws/src/main/webapp/index.html
- pom.xml
I add Graphene and normal JAX-WS Test(ClientIT).
It seems it needs complicated manners to do POST with WebDriver, so I only tested to make sure existing wsdl at Graphene Test.
> sorry, I'm new to WebDriver...
> Add JAX-WS Sample

- docker-jaxrs-app/pom.xml
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-war/pom.xml
- jpa/jpa-war/pom.xml
- kitchensink-html5-mobile/pom.xml
- logstash/pom.xml
- pom.xml
- ribbon-secured/pom.xml
- ribbon/pom.xml
```
modified:   docker-jaxrs-app/pom.xml
modified:   jpa-jaxrs-cdi/jpa-jaxrs-cdi-war/pom.xml
modified:   jpa/jpa-war/pom.xml
modified:   kitchensink-html5-mobile/pom.xml
modified:   logstash/pom.xml
modified:   pom.xml
modified:   ribbon-secured/pom.xml
modified:   ribbon/pom.xml
```
> Adding license missing in pom.xml files

- jpa-jaxrs-cdi/jpa-jaxrs-cdi-shrinkwrap/README.md
- jpa-jaxrs-cdi/jpa-jaxrs-cdi-war/README.md
- jpa/jpa-shrinkwrap/README.md
- jpa/jpa-war/README.md
- jsf/jsf-shrinkwrap/README.md
- jsf/jsf-war/README.md
```
modified:   jpa-jaxrs-cdi/jpa-jaxrs-cdi-shrinkwrap/README.md
modified:   jpa-jaxrs-cdi/jpa-jaxrs-cdi-war/README.md
modified:   jpa/jpa-shrinkwrap/README.md
modified:   jpa/jpa-war/README.md
modified:   jsf/jsf-shrinkwrap/README.md
modified:   jsf/jsf-war/README.md
```
> some readme adjusts

- datasource/datasource-subsystem/README.adoc
- datasource/datasource-subsystem/pom.xml
- datasource/datasource-subsystem/src/it/java/org/wildfly/swarm/examples/ds/subsystem/DatasourceIT.java
- datasource/datasource-subsystem/src/main/java/org/wildfly/swarm/examples/ds/subsystem/Main.java
- datasource/datasource-subsystem/src/main/resources/modules/com/mysql/main/module.xml
- datasource/datasource-subsystem/src/main/resources/modules/org/postgresql/main/module.xml
I add datasource fraction settings fro PostgreSQL and MySQL and update README.
It may be a little bit confusing for new -Swarm users  because I put together 3 datasource settings in Main.java.
> Add other database settings

- datasource/datasource-subsystem/pom.xml
- datasource/datasource-subsystem/src/main/java/org/wildfly/swarm/examples/ds/subsystem/XmlMain.java
- datasource/datasource-subsystem/src/main/resources/standalone.xml
> Update datasource example to demonstrate SWARM-14 

- arjuna/arjuna-shrinkwrap/README.md
- arjuna/arjuna-shrinkwrap/src/main/java/org/wildfly/swarm/examples/arjuna/MyResource.java
- arjuna/pom.xml
Can also confirm that property file issue appears fixed.
https://issues.jboss.org/browse/SWARM-241
> Merged in updated example

- jaxrs/README.adoc
See https://en.wiktionary.org/wiki/programmatically
> Fix typos in README

- messaging/messaging-simple/README.md
- messaging/messaging-simple/src/main/java/org/wildfly/swarm/examples/messaging/MyResource.java
- messaging/messaging-simple/src/main/java/org/wildfly/swarm/examples/messaging/MyService.java
* use JMS 2.0 API to remove boilerplate code
* updated Main code copy in README.md
> update messaging-simple example

- messaging/messaging-clustering/README.md
- messaging/messaging-clustering/pom.xml
- messaging/messaging-clustering/src/it/java/org/wildfly/swarm/it/messaging/MessagingApplicationIT.java
- messaging/messaging-clustering/src/main/java/org/wildfly/swarm/examples/messaging/clustering/Main.java
- messaging/messaging-clustering/src/main/java/org/wildfly/swarm/examples/messaging/clustering/MyResource.java
- messaging/messaging-clustering/src/main/java/org/wildfly/swarm/examples/messaging/clustering/MyService.java
- messaging/messaging-clustering/src/main/java/org/wildfly/swarm/examples/messaging/clustering/MyServiceActivator.java
- messaging/pom.xml
Add messaging-clustering examples that create a clustered JMS topic over
2 swarm servers
JIRA: https://issues.jboss.org/browse/SWARM-121
> [SWARM-121] Enable clustering for messaging

- camel/camel-cdi/README.md
- camel/camel-cxf-jaxrs/README.md
- camel/camel-cxf-jaxws/README.md
- camel/camel-jms/README.md
- camel/camel-mail/README.md
- camel/camel-mail/pom.xml
- camel/camel-mail/src/main/java/org/wildfly/swarm/examples/camel/mail/MailRouteBuilder.java
- camel/camel-mail/src/main/java/org/wildfly/swarm/examples/camel/mail/Main.java
- camel/camel-mail/src/test/java/org/wildfly/swarm/examples/camel/mail/CamelMailIT.java
- camel/pom.xml
https://issues.jboss.org/browse/SWARM-431
> [SWARM-431] Add example for camel-mail

- config-options/cdi-injection/pom.xml
- config-options/cdi-injection/src/main/java/org/wildfly/swarm/examples/jaxrs/cdi/Controller.java
Based on https://github.com/wildfly-swarm/wildfly-swarm-core/pull/34
> Update cdi-injections example.

- docker/docker-jaxrs-dockerfile/README.adoc
- docker/docker-jaxrs-dockerfile/docker/Dockerfile
- docker/docker-jaxrs-dockerfile/pom.xml
- docker/docker-jaxrs-dockerfile/src/main/java/org/wildfly/swarm/example/docker/JaxRsApplication.java
- docker/docker-jaxrs-dockerfile/src/main/java/org/wildfly/swarm/example/docker/MyResource.java
- docker/docker-jaxrs-dockerfile/src/main/java/org/wildfly/swarm/example/docker/SwarmMain.java
- docker/pom.xml
Added a docker example where the image is built from a Dockerfile. Intended to compliment to the docker-jaxrs example as many prefer to provide Dockerfiles instead of declaring it in their pom.xml.
> Docker jaxrs dockerfile

- logstash/events/src/main/java/org/wildfly/swarm/examples/netflix/ribbon/events/Main.java
- logstash/time/src/main/java/org/wildfly/swarm/examples/netflix/ribbon/time/Main.java
Updated deprecated org.wildfly.swarm.container.Container handler to org.wildfly.swarm.Swarm
> Updated deprecated org.wildfly.swarm.container.Container handler to org.wildfly.swarm.Swarm

- jaxrs/pom.xml
- jaxrs/zipkin/README.md
- jaxrs/zipkin/pom.xml
- jaxrs/zipkin/src/main/java/org/wildfly/swarm/examples/zipkin/HelloEndpoint.java
- jaxrs/zipkin/src/main/java/org/wildfly/swarm/examples/zipkin/Main.java
- jaxrs/zipkin/src/main/java/org/wildfly/swarm/examples/zipkin/RestApplication.java
https://issues.jboss.org/browse/SWARM-920
Example application with zipkin-jaxrs fraction reporting spans to zipkin server.
> zipkin-jaxrs fraction example

- camel/pom.xml
https://issues.jboss.org/browse/SWARM-457
> SWARM-457: Remove dependency on restlet springsource repo

- security/keycloak/README.md
- security/keycloak/pom.xml
- security/keycloak/realm/wildfly-swarm-keycloak-example-realm.json
- security/keycloak/src/main/java/org/wildfly/swarm/examples/keycloak/NonSecuredResource.java
- security/keycloak/src/main/java/org/wildfly/swarm/examples/keycloak/SecuredResource.java
- security/keycloak/src/main/resources/project-stages.yml
- security/keycloak/src/main/webapp/WEB-INF/keycloak.json
- security/pom.xml
Motivation
----------
Now Keycloak Fraction doesn't require main().
It's time to add Keyclaok Example.
Modifications
-------------
Add Keyclaok Example under security module.
Result
------
No impact to product, add example.
> SWARM-998: Add Keycloak Example

- docker/docker-jaxrs/README.adoc
- docker/docker-jaxrs/pom.xml
Adding notes on the docker profile in the `pom.xml` file
As well as using latest of fabric8 docker plugin, since the jolokia one is now fabric8
> Fabric8 Plugin usage 

- jaxrs/opentracing-hawkular/README.md
- jaxrs/opentracing-hawkular/pom.xml
- jaxrs/opentracing-hawkular/src/main/java/org/wildfly/swarm/examples/opentracing/hawkular/jaxrs/HelloEndpoint.java
- jaxrs/opentracing-hawkular/src/main/java/org/wildfly/swarm/examples/opentracing/hawkular/jaxrs/Main.java
- jaxrs/opentracing-hawkular/src/main/java/org/wildfly/swarm/examples/opentracing/hawkular/jaxrs/RestApplication.java
- jaxrs/pom.xml
on hold until implemented in main repo
> SWARM-946 | OpenTracing Hawkular example app

- base/src/main/java/org/wildfly/swarm/it/AbstractIntegrationTest.java
- config-options/cdi-injection/pom.xml
- config-options/cdi-injection/src/it/java/org/wildfly/swarm/examples/jaxrs/cdi/JAXRSApplicationIT.java
- config-options/cdi-injection/src/main/java/org/wildfly/swarm/examples/jaxrs/cdi/Controller.java
- jaxrs/health/src/it/java/org/wildfly/swarm/it/jaxrs/JAXRSHealthApplicationIT.java
- jaxrs/health/src/main/java/org/wildfly/swarm/examples/jaxrs/health/HealthCheckResource.java
- jaxrs/health/src/main/resources/project-defaults.yml
> SWARM-1116: Health API has moved to another package

- camel/camel-activemq/pom.xml
- camel/camel-swagger/pom.xml
Hold until wildfly-swarm/wildfly-swarm#340 is merged
> [SWARM-1075] Deprecate camel-other in favour of specific fractions

- config-options/README.adoc
- config-options/cdi-injection/README.adoc
Adds documentation to the top level config-options sample and the config-options/cdi-injection sample.
> SWARM-1603 Configuration Sample Documentation

- microprofile/README.md
Updated the link to MicroProfile.io to display correctly.
> SWARM-1615 Fixed MicroProfile link

- microprofile/README.md
- microprofile/pom.xml
- microprofile/src/main/fabric8/example-microprofile-deployment.yml
- microprofile/src/main/fabric8/example-microprofile-route.yml
- microprofile/src/main/fabric8/example-microprofile-svc.yml
Updated project to deploy to openshift.
> Microprofile4ocp

- management-console/README.md
- management-console/src/main/resources/project-defaults.yaml
Kept the password lower-case, a bit easier to type
> [SWARM-1896] Minor update to README and config

- microprofile-opentracing/README.md
- microprofile-opentracing/pom.xml
- microprofile-opentracing/src/main/java/org/wildfly/swarm/examples/microprofile/opentracing/MyApplication.java
- microprofile-opentracing/src/main/java/org/wildfly/swarm/examples/microprofile/opentracing/MyResource.java
- microprofile-opentracing/src/main/java/org/wildfly/swarm/examples/microprofile/opentracing/ServiceBean.java
- microprofile-opentracing/src/main/webapp/WEB-INF/beans.xml
- pom.xml
If you want to try it follow the instructions from existing opentracing example
> Microprofile OpenTracing example

- microprofile/src/main/webapp/WEB-INF/beans.xml
Fixes https://ci.wildfly-swarm.io/job/thorntail-examples-pull-request-linux/132/io.thorntail.examples$example-microprofile/console 
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Add beans.xml to microprofile example

- microprofile-opentracing/pom.xml
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Use jaeger fraction in mp-ot example

- management-console/README.md
> Fix typos in README.md

- security/ee-security-basic/README.md
- security/ee-security-basic/pom.xml
- security/ee-security-basic/src/it/java/org/wildfly/swarm/it/eesecurity/SecuredApplicationIT.java
- security/ee-security-basic/src/main/java/org/wildfly/examples/swarm/eesecurity/CustomIdentityStore.java
- security/ee-security-basic/src/main/java/org/wildfly/examples/swarm/eesecurity/JaxrsActivator.java
- security/ee-security-basic/src/main/java/org/wildfly/examples/swarm/eesecurity/SecuredResource.java
- security/ee-security-basic/src/main/java/org/wildfly/examples/swarm/eesecurity/SecuredServlet.java
- security/ee-security-basic/src/main/webapp/WEB-INF/jboss-web.xml
- security/pom.xml
Example of secured servlet via Java EE 8 Security annotations.
> Add Java EE 8 Security example
